# Generated by Django 3.0.7 on 2020-08-31 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/picture/'),
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('matricule', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
